version: '3.9'
services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.19.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/chat_clip/deployments/nginx/nginx.conf:/etc/nginx/nginx.conf

  mysql:
    container_name: chat_ai_mysql
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ne1zoP1GJ8T9XXF5
      MYSQL_DATABASE: chat_ai_production
      MYSQL_USER: chat_ai
      MYSQL_PASSWORD: fm4dgFTyv9hNLCIF
    command:
      - --authentication_policy=mysql_native_password
      - --sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: chat_clip_redis
    image: redis:7.0
    restart: always
    volumes:
      - redis_data:/data
  
  backend:
    container_name: chat_clip_backend
    image: swr.cn-north-4.myhuaweicloud.com/registry-huawei/effyic/chat_clip:latest
    restart: always
    pull_policy: always
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: true
      SECRET_KEY_BASE: 38bf2bff9d20e06409cd26d3e726f840bf3161cdccaa0e28b560b066e7eef34c4bec7733ba6f8f01dcaeb6425d26d1dc0c4c511c7dc30ccfd63b9eb493583274
      DATABASE_URL: mysql2://chat_clip:fm4dgFTyv9hNLCIF@mysql/chat_clip_production
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_URL: http://8.218.227.49
      OPENAI_API_KEY: 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
      JDCLOUD_ACCESS_KEY_ID: 01DB61AA138CBB616C0DB0865B24E143
      JDCLOUD_SECRET_ACCESS_KEY: FE8FC0E814B2E932A601EEF92C481607
      JDCLOUD_ENDPOINT: https://s3.cn-north-1.jdcloud-oss.com
      JDCLOUD_REGION: cn-north-1
      JDCLOUD_BUCKET: effyic-dev
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  redis_data:
